### PR TITLE
v2 improvements - web

### PR DESCRIPTION
**Pull request by Krizzu**
Summary:
---------

Next round of improvements for v2:

- [X] Web example app
- [x] Web to use [idb-keyval as storage](https://www.npmjs.com/package/idb-keyval)
- [X] Unit tests for web module

Test Plan:
----------

Green CI.

### CODE REVIEW

**Comment by vomchik** [comment]
@Krizzu Could you please publish RC2, i need your fix with __DEV__ variable. Thanks.

**Comment by Krizzu** [comment]
> @Krizzu Could you publish RC2, please. I need your fix with `__DEV__` variable. Thanks.

Yes, I plan to do this later today

**Comment by vomchik** [comment]
Thanks a lot!

**Comment by Krizzu** [comment]
> Thanks a lot!

Sorry, seems like I'm bit delayed.

**Comment by vomchik** [comment]
Thanks!

**Comment by vomchik** [comment]
@Krizzu Hi! Any news about the new RC?

**Comment by Krizzu** [comment]
@vomchik 
Just released RC.2!

**Comment by soroushm** [comment]
AsyncStorage removed from react-native-web since version 12
https://github.com/necolas/react-native-web/releases

**Comment by soroushm** [comment]
Finnaly got the right package for web

alias: {
        // Support React Native Web
        // https://www.smashingmagazine.com/2016/08/a-glimpse-into-the-future-with-react-native-for-web/
       ` '@react-native-community/async-storage': 'redux-persist/lib/storage',`

**Pull request merged**
