### PR TITLE
Fix API typos

### PR DESCRIPTION
**Pull request by TheDSCPL**
Summary:
---------

Fix API typos

Test Plan:
----------
No test required

### CODE REVIEW

**Comment by Krizzu** [comment]
Can you explain why you think this is a typo?

**Comment by TheDSCPL** [comment]
"can be also reject**s**"? It looks like the author wanted to type "can be also reject**ed**". I didn't change to that because "can be also" is totally unnecessary due to "in case of". If you really want the "can also be" to stay, then it should at least be "can be also reject**ed**"

**Comment by TheDSCPL** [comment]
On second thought it actually should be "rejecting in case(...)" to match the tense from the previous line which starts with "resolving"

**Comment by TheDSCPL** [comment]
I updated the PR to "can also be rejected" for middle ground :)

**Comment by Krizzu** [comment]
> I updated the PR to "can also be rejected" for middle ground :)

Appreciated 🙏

**Pull request merged**
